version: '3.8'

services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: coruja-nginx
    restart: unless-stopped
    hostname: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_data:/var/log/nginx/conf.d:ro
    depends_on:
      - application
    networks:
      - backend

  database:
    image: mysql:8.0
    container_name: coruja-database
    restart: unless-stopped
    hostname: database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./database_data:/docker-entrypoint-initdb.d
    expose:
      - '3306'
    networks:
      - backend

  application:
    image: coruja-application
    container_name: coruja-application
    hostname: application
    entrypoint: sh entrypoint.sh
    build: .
    expose:
      - '8080'
    depends_on:
      - database
    networks:
      - backend

networks:
  backend:
    name: coruja-backend
    driver: bridge

volumes:
  database_data:
    driver: local
  nginx_data:
    driver: local
